package com.example.farmdatapod.models

data class OrganisationCustomerRequestModel(
    val company_name: String,
    val county: String,
    val customer_code: String,
    val date_of_birth1: String,
    val date_of_birth2: String,
    val date_of_birth3: String,
    val date_of_registration: String,
    val email: String,
    val email1: String,
    val email2: String,
    val email3: String,
    val gender1: String,
    val gender2: String,
    val gender3: String,
    val id_number1: Int,
    val id_number2: Int,
    val id_number3: Int,
    val last_name1: String,
    val last_name2: String,
    val last_name3: String,
    val other_name1: String,
    val other_name2: String,
    val other_name3: String,
    val phone_number: Int,
    val phone_number1: Long,
    val phone_number2: Long,
    val phone_number3: Long,
    val products: List<Product>,
    val registration_number: Int,
    val sector: String,
    val sub_county: String,
    val village: String,
    val ward: String
)