package com.example.farmdatapod.models

data class ProducerBiodataRequest(
    val id: Long?,
    val other_name: String?,
    val last_name: String?,
    val farmer_code: String?,
    val id_number: String?,
    val date_of_birth: String?,
    val email: String?,
    val phone_number: String?,
    val location: String?,
    val hub: String?,
    val buying_center: String?,
    val gender: String?,
    val education_level: String?,
    val county: String?,
    val sub_county: String?,
    val ward: String?,
    val village: String?,
    val primary_producer: List<Map<String, Any>>?,
    val total_land_size: String?,
    val cultivate_land_size: String?,
    val homestead_size: String?,
    val uncultivated_land_size: String?,
    val farm_accessibility: String?,
    val number_of_family_workers: String?,
    val number_of_hired_workers: String?,
    val farmer_interest_in_extension: String?,
    val access_to_irrigation: String?,
    val crop_list: String?,
    val knowledge_related: String?,
    val soil_related: String?,
    val compost_related: String?,
    val nutrition_related: String?,
    val pests_related: String?,
    val disease_related: String?,
    val quality_related: String?,
    val market_related: String?,
    val food_loss_related: String?,
    val finance_related: String?,
    val weather_related: String?,
    val dairy_cattle: String?,
    val beef_cattle: String?,
    val sheep: String?,
    val goats: String?,
    val pigs: String?,
    val poultry: String?,
    val camels: String?,
    val aquaculture: String?,
    val rabbits: String?,
    val beehives: String?,
    val donkeys: String?,
    val housing_type: String? = "Yes",
    val housing_floor: String? = "Yes",
    val housing_roof: String? = "Yes",
    val lighting_fuel: String? = "Yes",
    val cooking_fuel: String? = "Yes",
    val water_filter: String? = "Yes",
    val water_tank_greater_than_5000lts: String? = "Yes",
    val hand_washing_facilities: String? = "Yes",
    val ppes: String? = "Standard PPE",
    val water_well_or_weir: String? = "Available",
    val irrigation_pump: String? = "Available",
    val harvesting_equipment: String? = "Available",
    val transportation_type: String? = "Truck",
    val toilet_floor: String? = "Concrete",
    val commercialProduces: List<Map<String, Any?>>?,
    val domesticProduces: List<Map<String, Any?>>?,
    val bank_name: String?, // Added
    val bank_account_number: String?, // Added
    val bank_account_holder: String?, // Added
    val mobile_money_provider: String?, // Added
    val mobile_money_number: String? // Added
)